CREATE SCHEMA IF NOT EXISTS `tonghua` DEFAULT CHARACTER SET utf8 ;
CREATE USER 'tonghua'@'localhost' IDENTIFIED BY 'adminTTDEMO';
GRANT ALL PRIVILEGES ON tonghua.* TO 'tonghua'@'localhost' IDENTIFIED BY 'adminTTDEMO' WITH GRANT OPTION;
FLUSH PRIVILEGES;
